subdomain = [
    'ww0', 'lisa', 'rdp', 'helpdesk', 'media', 'mx03', 'echo', 'r', 'www1', 'ns6', 'faq', 'kb', 'autodiscover',
    'autoconfig', 'unix', 'signup', 'web2', 'www4', 'tw', 'ns', 'extranet', 'www', 'origin', 'vip', 'nat', 'news',
    'partner', 'demon', 'tunnel', 'sitebuilder', 'thumbs', 's', 'docs', 'edu', 'loghost', 'ftp2', 'oldsite', 'svn',
    'sv', 'firewall', 't', 'radio', 'orion', 'assets', 'ppp', 'portal', 'pub', 'in', 'pda', 'testsite', 'nagios',
    'post', 'www6', 'q', 'new', 'videos', 'pro', 'cdn', 'gateway', 'login', 'snmp', 'vps1', 'ww2', 'w3', 'intranet',
    'desktop', 'ecommerce', 'squirrelmail', 'ci', 'images', 'track', 'chimera', 'ww02', 'm', 'it', 'webmin', 'panel',
    'exchange', 'mx-a', 'rt', 'mx02', 'dns1', 'blog', 'sftp', 'vpn2', 'rss', 's4', 'ipv6', 'preprod', 'gallery', 's2',
    'ektron', 'forum', 'project', 'sslvpn', 'email', 'test', 'trac', 'sites', 'travel', 'devel', 'store', 'folders',
    'list', 'eaccess', 'pegasus', 'stat', 'admin', 'www2', 'legacy', 'soporte', 'start', 'mail2', 'job', 'outgoing',
    'radius', 'dl', 'localhost', 'partners', 'foros', 'op', 'network', 'vpn', 'beta', 'dev2', 'oa', 'voip', 'noc',
    'shell', 'ww01', 'net', 'ops', 'correo', 'secure', 'video', 'acceptatie', 'jira', 'sql', 'ns3', 'doc', 'auto',
    'ftpd', 'phpmyadmin', 'e', 'img', 'ad', 'training', 'vps', 'v', 'ftp1', 'gw', 'sip', 'webmail', 'dns', 'incoming',
    'kerberos', 'telework', 'fileserver', 'static', 'calendar', 'vps2', 'router', 'vmware', 'smtp2', 'web03', 'ns0',
    'ww', 'demo2', 'ip6', 'test1', 'io', 'office2', 'payment', 'client', 'netmail', 'networks', 'classroom', 'lms',
    'personal', 'software', 'chronos', 'vpn3', 'train', 'remote', 'clientes', 'testing', 'web01', 'iphone', 'monitor',
    'auth', 'ftpadmin', 'game', 'squirrel', 'ldap', 'x', 'jobs', 'ns03', 'accounts', 'mx01', 'lists', 'fax', 'file',
    'newmail', 'mssql', 'test3', 'nt', 'tracking', 'windows', 'neon', 'foro', 'tech', 'tftp', 'private', 'status',
    'ns11', 'win', 'affiliates', 'www02', 'ns8', 'wifi', 'siteadmin', 'lyncdiscover', 'www3', 'parallels',
    'demostration', 'apollo', 'direct', 'es', 'on', 'root', 'alpha', 'skype', 'pruebas', 'backup', 'direct-connect',
    'foto', 'lab', 'app', 'ssl', 'vm', 'ru', 'wp', 'uploads', 'sms', 'vod', 'netscaler', 'redmine', 'isa', 'vle', 'mx',
    'oldmail', 'stats', 'de', 'free', 'dns2', 'g', 'site', 'f', 'reports', 'facebook', 'sharepoint', 'crm', 'preview',
    'webstore', 'ns12', 'remote2', 'pp', 'os', 'erp', 'jupiter', 'clients', 'work', 'ns01', 'operation', 'uk', 'cp',
    'smtp3', 'telewerk', 'ads', 'linux', 'osx', 'social', 'pop', 'drupal', 'fr', 'jboss2', 'promo', 'webstats', 'dns3',
    'internal', 'online', 'u', 'ventas', 'smtp1', 'shopping', 'ww1', 'webservices', 'dmz', 'payments', 'share', 'test2',
    'i', 'directory', 'domain', 'av', 'imap', 'sso', 'mx3', 'uat', 'demo', 'la', 'team', 'storage', 'web0', 'moodle',
    'js', 'repos', 'oracle', 'static2', 'ipmi', 'external', 'b', 'l', 'log', 'wwwm', 'p', 'ipsec', 'inmuebles', 'links',
    'w', 'is', 'stage', 'postmaster', 'old', 'php', 'nl', 'postgres', 'event', 'wordpress', 'tutorials', 'jabber',
    'static1', 'projects', 'painel', 'ts', 'db', 'portfolio', 'accounting', 'files', 'ras', 'n', 'examples',
    'affiliate', 'games', 'production', 'cdn1', 'ayuda', 'english', 'freebsd', 'shop', 'intra', 'eng', 'sp', 'mysql',
    'dev1', 'downloads', 'ra', 'elearning', 'spam', 'report', 'pbx', 'diana', 'postal', 'download', 'dev01', 'web02',
    'b2b', 'library', 'staging', 'j', 'ssh', 'default', 'ns2', 'win32', 'alumni', 'feedback', 'nelson', 'ora', 'mail',
    'live', 'administrator', 'prueba', 'webdisk', 'solaris', 'en', 'prod', 'users', 'sqlserver', 'ipv4', 'office',
    'forums', 'whm', 'poczta', 'host', 'ns02', 'adserver', 'vc', 'paralel', 'example', 'redirect', 'www5', 'repo',
    'user', 'developers', 'jboss', 'server', 'mysql2', 'o', 'vms', 'events', 'support', 'ns7', 'operations', 'fs',
    'mail3', 'pr', 'vpn1', 'mx-b', 'smtp', 'citrix', 'newsgroups', 'dialin', 'ntp1', 'my', 'k', 'mx2', 'help', 'jp',
    'info', 'art', 'lib', 'descargas', 'feeds', 'dns4', 'ww03', 'testweb', 'pendrell', 'search', 'mobile', 'postgresql',
    'ex', 'fb', 'ns1', 'a', 'www-test', 'archive', 'update', 'novell', 'ns4', 'adm', 'vb', 'dc', 'pm', 'qa', 'ipfixe',
    'wc', 's3', 'fw', 'research', 'imogen', 'pma', 'ns10', 'pgsql', 'bbs', 'pcanywhere', 'link', 'labs', 'dev',
    'design', 'finance', 'newsletter', 'ja', 'tickets', 'sport', 'blogs', 'ns5', 'sun', 'v2', 'survey', 'forms', 'api',
    'virtual', 'munin', 'tools', 'wsus', 'upload', 'development', 'wiki', 'wap', 'ftp', 'local', 'photos', 'outlook',
    'irc', 'ann', 'newsite', 'wwwold', 'dbs', 'time', 'up', 'tracker', 'www0', 'tv', 's1', 'speedtest', 'ntp', 'oldwww',
    'www01', 'cisco', 'home', 'agenda', 'galeria', 'tfs', 'music', 'web1', 'interno', 'www03', 'ticket', 'mail1',
    'postman', 'public', 'pay', 'wwww', 'cdn2', 'network-ip', 'ip', 'access', 'pt', 'nas', 'vnc', 'vista', 'ws',
    'proxy', 'relay', 'cms', 'apps', 'rtmp', 'ar', 'mx1', 'sports', 'st', 'photo', 'chat', 'ww3', 'ircd', 'cpanel',
    'openbsd', 'analytics', 'mx0', 'ou', 'ox', 'atlas', 'phoenix', 'pop3', 'service', 'press', 'temp', 'xml', 'staff',
    'register', 'owa', 'us', 'web', 'www7'
]
