from .asp import asp_login
from .aspx import aspx_login
from .brf import brf_login
from .cfm import cfm_login
from .cgi import cgi_login
from .html import html_login
from .js import js_login
from .php import php_login
from .slash import slash_login
